export {default as VRCarContent}  from './VRCarContent'
export {default as RightInfoErea} from './RightInfoErea'
export {default as InOrOutSideBtn} from './InOrOutSideBtn'
export {default as PersonInfo} from './PlicyComponent/PersonInfo'
export {default as PlicyPlan} from './PlicyComponent/PlicyPlan'
export {default as FinalPlan} from './PlicyComponent/FinalPlan'
export {default as CarFooter} from './CarFooter'